-- Postgres catch-up migration generated by scripts/generate-postgres-catchup.js
-- Brings a Supabase DB up to the complete runtime schema. Idempotent & safe to re-run.
-- Paste into the Supabase SQL editor and run.

-- activity_log
ALTER TABLE "activity_log" ADD COLUMN IF NOT EXISTS "id" BIGINT;
ALTER TABLE "activity_log" ADD COLUMN IF NOT EXISTS "user_id" TEXT;
ALTER TABLE "activity_log" ADD COLUMN IF NOT EXISTS "device_id" TEXT;
ALTER TABLE "activity_log" ADD COLUMN IF NOT EXISTS "action" TEXT;
ALTER TABLE "activity_log" ADD COLUMN IF NOT EXISTS "details" TEXT;
ALTER TABLE "activity_log" ADD COLUMN IF NOT EXISTS "ip_address" TEXT;
ALTER TABLE "activity_log" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "activity_log" ADD COLUMN IF NOT EXISTS "workspace_id" TEXT;
ALTER TABLE "activity_log" ADD COLUMN IF NOT EXISTS "organization_id" TEXT;
ALTER TABLE "activity_log" ADD COLUMN IF NOT EXISTS "acting_user_id" TEXT;
ALTER TABLE "activity_log" ADD COLUMN IF NOT EXISTS "was_acting_as" BIGINT DEFAULT 0;

-- agency_notifications
ALTER TABLE "agency_notifications" ADD COLUMN IF NOT EXISTS "id" BIGINT;
ALTER TABLE "agency_notifications" ADD COLUMN IF NOT EXISTS "workspace_id" TEXT;
ALTER TABLE "agency_notifications" ADD COLUMN IF NOT EXISTS "token_id" TEXT;
ALTER TABLE "agency_notifications" ADD COLUMN IF NOT EXISTS "playlist_id" TEXT;
ALTER TABLE "agency_notifications" ADD COLUMN IF NOT EXISTS "action" TEXT;
ALTER TABLE "agency_notifications" ADD COLUMN IF NOT EXISTS "content_id" TEXT;
ALTER TABLE "agency_notifications" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "agency_notifications" ADD COLUMN IF NOT EXISTS "sent_at" BIGINT;

-- ai_settings
ALTER TABLE "ai_settings" ADD COLUMN IF NOT EXISTS "workspace_id" TEXT;
ALTER TABLE "ai_settings" ADD COLUMN IF NOT EXISTS "base_url" TEXT;
ALTER TABLE "ai_settings" ADD COLUMN IF NOT EXISTS "api_key_enc" TEXT;
ALTER TABLE "ai_settings" ADD COLUMN IF NOT EXISTS "model" TEXT;
ALTER TABLE "ai_settings" ADD COLUMN IF NOT EXISTS "image_base_url" TEXT;
ALTER TABLE "ai_settings" ADD COLUMN IF NOT EXISTS "image_model" TEXT;
ALTER TABLE "ai_settings" ADD COLUMN IF NOT EXISTS "image_provider" TEXT;
ALTER TABLE "ai_settings" ADD COLUMN IF NOT EXISTS "image_api_key_enc" TEXT;
ALTER TABLE "ai_settings" ADD COLUMN IF NOT EXISTS "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);

-- alert_configs
ALTER TABLE "alert_configs" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "alert_configs" ADD COLUMN IF NOT EXISTS "user_id" TEXT;
ALTER TABLE "alert_configs" ADD COLUMN IF NOT EXISTS "alert_type" TEXT;
ALTER TABLE "alert_configs" ADD COLUMN IF NOT EXISTS "enabled" BIGINT DEFAULT 1;
ALTER TABLE "alert_configs" ADD COLUMN IF NOT EXISTS "config" TEXT DEFAULT '{}';
ALTER TABLE "alert_configs" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "alert_configs" ADD COLUMN IF NOT EXISTS "workspace_id" TEXT;

-- api_token_targets
ALTER TABLE "api_token_targets" ADD COLUMN IF NOT EXISTS "token_id" TEXT;
ALTER TABLE "api_token_targets" ADD COLUMN IF NOT EXISTS "playlist_id" TEXT;
ALTER TABLE "api_token_targets" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);

-- api_tokens
ALTER TABLE "api_tokens" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "api_tokens" ADD COLUMN IF NOT EXISTS "token_hash" TEXT;
ALTER TABLE "api_tokens" ADD COLUMN IF NOT EXISTS "prefix" TEXT;
ALTER TABLE "api_tokens" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "api_tokens" ADD COLUMN IF NOT EXISTS "user_id" TEXT;
ALTER TABLE "api_tokens" ADD COLUMN IF NOT EXISTS "workspace_id" TEXT;
ALTER TABLE "api_tokens" ADD COLUMN IF NOT EXISTS "scope" TEXT DEFAULT 'read';
ALTER TABLE "api_tokens" ADD COLUMN IF NOT EXISTS "auto_publish" BIGINT DEFAULT 0;
ALTER TABLE "api_tokens" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "api_tokens" ADD COLUMN IF NOT EXISTS "last_used_at" BIGINT;
ALTER TABLE "api_tokens" ADD COLUMN IF NOT EXISTS "revoked_at" BIGINT;

-- assignments
ALTER TABLE "assignments" ADD COLUMN IF NOT EXISTS "id" BIGINT;
ALTER TABLE "assignments" ADD COLUMN IF NOT EXISTS "device_id" TEXT;
ALTER TABLE "assignments" ADD COLUMN IF NOT EXISTS "content_id" TEXT;
ALTER TABLE "assignments" ADD COLUMN IF NOT EXISTS "widget_id" TEXT;
ALTER TABLE "assignments" ADD COLUMN IF NOT EXISTS "zone_id" TEXT;
ALTER TABLE "assignments" ADD COLUMN IF NOT EXISTS "sort_order" BIGINT DEFAULT 0;
ALTER TABLE "assignments" ADD COLUMN IF NOT EXISTS "duration_sec" BIGINT DEFAULT 10;
ALTER TABLE "assignments" ADD COLUMN IF NOT EXISTS "schedule_start" TEXT;
ALTER TABLE "assignments" ADD COLUMN IF NOT EXISTS "schedule_end" TEXT;
ALTER TABLE "assignments" ADD COLUMN IF NOT EXISTS "schedule_days" TEXT;
ALTER TABLE "assignments" ADD COLUMN IF NOT EXISTS "enabled" BIGINT DEFAULT 1;
ALTER TABLE "assignments" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "assignments" ADD COLUMN IF NOT EXISTS "muted" BIGINT DEFAULT 0;

-- content
ALTER TABLE "content" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "content" ADD COLUMN IF NOT EXISTS "user_id" TEXT;
ALTER TABLE "content" ADD COLUMN IF NOT EXISTS "filename" TEXT;
ALTER TABLE "content" ADD COLUMN IF NOT EXISTS "filepath" TEXT DEFAULT '';
ALTER TABLE "content" ADD COLUMN IF NOT EXISTS "mime_type" TEXT;
ALTER TABLE "content" ADD COLUMN IF NOT EXISTS "file_size" BIGINT DEFAULT 0;
ALTER TABLE "content" ADD COLUMN IF NOT EXISTS "duration_sec" DOUBLE PRECISION;
ALTER TABLE "content" ADD COLUMN IF NOT EXISTS "thumbnail_path" TEXT;
ALTER TABLE "content" ADD COLUMN IF NOT EXISTS "width" BIGINT;
ALTER TABLE "content" ADD COLUMN IF NOT EXISTS "height" BIGINT;
ALTER TABLE "content" ADD COLUMN IF NOT EXISTS "remote_url" TEXT;
ALTER TABLE "content" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "content" ADD COLUMN IF NOT EXISTS "team_id" TEXT;
ALTER TABLE "content" ADD COLUMN IF NOT EXISTS "folder" TEXT;
ALTER TABLE "content" ADD COLUMN IF NOT EXISTS "folder_id" TEXT;
ALTER TABLE "content" ADD COLUMN IF NOT EXISTS "workspace_id" TEXT;

-- content_folders
ALTER TABLE "content_folders" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "content_folders" ADD COLUMN IF NOT EXISTS "user_id" TEXT;
ALTER TABLE "content_folders" ADD COLUMN IF NOT EXISTS "parent_id" TEXT;
ALTER TABLE "content_folders" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "content_folders" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "content_folders" ADD COLUMN IF NOT EXISTS "workspace_id" TEXT;

-- device_fingerprints
ALTER TABLE "device_fingerprints" ADD COLUMN IF NOT EXISTS "fingerprint" TEXT;
ALTER TABLE "device_fingerprints" ADD COLUMN IF NOT EXISTS "device_id" TEXT;
ALTER TABLE "device_fingerprints" ADD COLUMN IF NOT EXISTS "user_id" TEXT;
ALTER TABLE "device_fingerprints" ADD COLUMN IF NOT EXISTS "first_seen" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "device_fingerprints" ADD COLUMN IF NOT EXISTS "last_seen" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);

-- device_group_members
ALTER TABLE "device_group_members" ADD COLUMN IF NOT EXISTS "device_id" TEXT;
ALTER TABLE "device_group_members" ADD COLUMN IF NOT EXISTS "group_id" TEXT;

-- device_groups
ALTER TABLE "device_groups" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "device_groups" ADD COLUMN IF NOT EXISTS "user_id" TEXT;
ALTER TABLE "device_groups" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "device_groups" ADD COLUMN IF NOT EXISTS "color" TEXT DEFAULT '#3B82F6';
ALTER TABLE "device_groups" ADD COLUMN IF NOT EXISTS "playlist_id" TEXT;
ALTER TABLE "device_groups" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "device_groups" ADD COLUMN IF NOT EXISTS "workspace_id" TEXT;

-- device_status_log
ALTER TABLE "device_status_log" ADD COLUMN IF NOT EXISTS "id" BIGINT;
ALTER TABLE "device_status_log" ADD COLUMN IF NOT EXISTS "device_id" TEXT;
ALTER TABLE "device_status_log" ADD COLUMN IF NOT EXISTS "status" TEXT;
ALTER TABLE "device_status_log" ADD COLUMN IF NOT EXISTS "timestamp" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);

-- device_telemetry
ALTER TABLE "device_telemetry" ADD COLUMN IF NOT EXISTS "id" BIGINT;
ALTER TABLE "device_telemetry" ADD COLUMN IF NOT EXISTS "device_id" TEXT;
ALTER TABLE "device_telemetry" ADD COLUMN IF NOT EXISTS "battery_level" BIGINT;
ALTER TABLE "device_telemetry" ADD COLUMN IF NOT EXISTS "battery_charging" BIGINT DEFAULT 0;
ALTER TABLE "device_telemetry" ADD COLUMN IF NOT EXISTS "storage_free_mb" BIGINT;
ALTER TABLE "device_telemetry" ADD COLUMN IF NOT EXISTS "storage_total_mb" BIGINT;
ALTER TABLE "device_telemetry" ADD COLUMN IF NOT EXISTS "ram_free_mb" BIGINT;
ALTER TABLE "device_telemetry" ADD COLUMN IF NOT EXISTS "ram_total_mb" BIGINT;
ALTER TABLE "device_telemetry" ADD COLUMN IF NOT EXISTS "cpu_usage" DOUBLE PRECISION;
ALTER TABLE "device_telemetry" ADD COLUMN IF NOT EXISTS "wifi_ssid" TEXT;
ALTER TABLE "device_telemetry" ADD COLUMN IF NOT EXISTS "wifi_rssi" BIGINT;
ALTER TABLE "device_telemetry" ADD COLUMN IF NOT EXISTS "uptime_seconds" BIGINT;
ALTER TABLE "device_telemetry" ADD COLUMN IF NOT EXISTS "reported_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);

-- devices
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "user_id" TEXT;
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "name" TEXT DEFAULT 'Unnamed Display';
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "pairing_code" TEXT;
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "status" TEXT DEFAULT 'offline';
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "last_heartbeat" BIGINT;
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "ip_address" TEXT;
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "android_version" TEXT;
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "app_version" TEXT;
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "screen_width" BIGINT;
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "screen_height" BIGINT;
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "playlist_id" TEXT;
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "layout_id" TEXT;
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "timezone" TEXT DEFAULT 'UTC';
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "reported_timezone" TEXT;
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "reported_utc" BIGINT;
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "reported_at" BIGINT;
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "wall_id" TEXT;
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "team_id" TEXT;
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "notes" TEXT;
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "orientation" TEXT DEFAULT 'landscape';
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "default_content_id" TEXT;
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "device_token" TEXT;
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "sort_order" BIGINT DEFAULT 0;
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "workspace_id" TEXT;

-- hardware_orders
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "id" BIGINT;
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "order_number" TEXT;
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "user_id" TEXT;
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "stripe_session_id" TEXT;
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "stripe_payment_intent" TEXT;
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "stripe_refund_id" TEXT;
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "customer_name" TEXT DEFAULT '';
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "customer_email" TEXT;
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "customer_phone" TEXT;
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "vat_number" TEXT;
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "shipping_address_line1" TEXT DEFAULT '';
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "shipping_address_line2" TEXT;
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "city" TEXT DEFAULT '';
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "postcode" TEXT DEFAULT '';
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "country" TEXT DEFAULT '';
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "quantity" BIGINT DEFAULT 1;
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "subtotal" BIGINT DEFAULT 0;
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "tax" BIGINT DEFAULT 0;
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "total" BIGINT DEFAULT 0;
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "currency" TEXT DEFAULT 'gbp';
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "status" TEXT DEFAULT 'paid';
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "tracking_number" TEXT;
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "courier" TEXT;
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "notes" TEXT;
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "shipped_email_sent_at" BIGINT;
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);

-- kiosk_pages
ALTER TABLE "kiosk_pages" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "kiosk_pages" ADD COLUMN IF NOT EXISTS "user_id" TEXT;
ALTER TABLE "kiosk_pages" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "kiosk_pages" ADD COLUMN IF NOT EXISTS "config" TEXT DEFAULT '{}';
ALTER TABLE "kiosk_pages" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "kiosk_pages" ADD COLUMN IF NOT EXISTS "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "kiosk_pages" ADD COLUMN IF NOT EXISTS "workspace_id" TEXT;

-- layout_zones
ALTER TABLE "layout_zones" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "layout_zones" ADD COLUMN IF NOT EXISTS "layout_id" TEXT;
ALTER TABLE "layout_zones" ADD COLUMN IF NOT EXISTS "name" TEXT DEFAULT 'Zone';
ALTER TABLE "layout_zones" ADD COLUMN IF NOT EXISTS "x_percent" DOUBLE PRECISION DEFAULT 0;
ALTER TABLE "layout_zones" ADD COLUMN IF NOT EXISTS "y_percent" DOUBLE PRECISION DEFAULT 0;
ALTER TABLE "layout_zones" ADD COLUMN IF NOT EXISTS "width_percent" DOUBLE PRECISION DEFAULT 100;
ALTER TABLE "layout_zones" ADD COLUMN IF NOT EXISTS "height_percent" DOUBLE PRECISION DEFAULT 100;
ALTER TABLE "layout_zones" ADD COLUMN IF NOT EXISTS "z_index" BIGINT DEFAULT 0;
ALTER TABLE "layout_zones" ADD COLUMN IF NOT EXISTS "zone_type" TEXT DEFAULT 'content';
ALTER TABLE "layout_zones" ADD COLUMN IF NOT EXISTS "fit_mode" TEXT DEFAULT 'contain';
ALTER TABLE "layout_zones" ADD COLUMN IF NOT EXISTS "background_color" TEXT DEFAULT '#000000';
ALTER TABLE "layout_zones" ADD COLUMN IF NOT EXISTS "sort_order" BIGINT DEFAULT 0;

-- layouts
ALTER TABLE "layouts" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "layouts" ADD COLUMN IF NOT EXISTS "user_id" TEXT;
ALTER TABLE "layouts" ADD COLUMN IF NOT EXISTS "team_id" TEXT;
ALTER TABLE "layouts" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "layouts" ADD COLUMN IF NOT EXISTS "width" BIGINT DEFAULT 1920;
ALTER TABLE "layouts" ADD COLUMN IF NOT EXISTS "height" BIGINT DEFAULT 1080;
ALTER TABLE "layouts" ADD COLUMN IF NOT EXISTS "is_template" BIGINT DEFAULT 0;
ALTER TABLE "layouts" ADD COLUMN IF NOT EXISTS "template_category" TEXT;
ALTER TABLE "layouts" ADD COLUMN IF NOT EXISTS "thumbnail_data" TEXT;
ALTER TABLE "layouts" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "layouts" ADD COLUMN IF NOT EXISTS "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "layouts" ADD COLUMN IF NOT EXISTS "workspace_id" TEXT;

-- order_items
ALTER TABLE "order_items" ADD COLUMN IF NOT EXISTS "id" BIGINT;
ALTER TABLE "order_items" ADD COLUMN IF NOT EXISTS "order_id" BIGINT;
ALTER TABLE "order_items" ADD COLUMN IF NOT EXISTS "product_id" TEXT;
ALTER TABLE "order_items" ADD COLUMN IF NOT EXISTS "quantity" BIGINT DEFAULT 1;
ALTER TABLE "order_items" ADD COLUMN IF NOT EXISTS "unit_price" BIGINT;
ALTER TABLE "order_items" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);

-- organization_members
ALTER TABLE "organization_members" ADD COLUMN IF NOT EXISTS "id" BIGINT;
ALTER TABLE "organization_members" ADD COLUMN IF NOT EXISTS "organization_id" TEXT;
ALTER TABLE "organization_members" ADD COLUMN IF NOT EXISTS "user_id" TEXT;
ALTER TABLE "organization_members" ADD COLUMN IF NOT EXISTS "role" TEXT DEFAULT 'org_admin';
ALTER TABLE "organization_members" ADD COLUMN IF NOT EXISTS "invited_by" TEXT;
ALTER TABLE "organization_members" ADD COLUMN IF NOT EXISTS "joined_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);

-- organizations
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "slug" TEXT;
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "owner_user_id" TEXT;
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "plan_id" TEXT DEFAULT 'free';
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "stripe_customer_id" TEXT;
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "stripe_subscription_id" TEXT;
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "subscription_status" TEXT DEFAULT 'active';
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "subscription_ends" BIGINT;
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "grace_period_ends" BIGINT;
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "locked_at" BIGINT;
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "default_brand_name" TEXT;
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "default_logo_url" TEXT;
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "default_primary_color" TEXT;
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);

-- plans
ALTER TABLE "plans" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "plans" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "plans" ADD COLUMN IF NOT EXISTS "display_name" TEXT;
ALTER TABLE "plans" ADD COLUMN IF NOT EXISTS "max_devices" BIGINT DEFAULT 2;
ALTER TABLE "plans" ADD COLUMN IF NOT EXISTS "max_storage_mb" BIGINT DEFAULT 500;
ALTER TABLE "plans" ADD COLUMN IF NOT EXISTS "remote_control" BIGINT DEFAULT 0;
ALTER TABLE "plans" ADD COLUMN IF NOT EXISTS "remote_url" BIGINT DEFAULT 0;
ALTER TABLE "plans" ADD COLUMN IF NOT EXISTS "priority_support" BIGINT DEFAULT 0;
ALTER TABLE "plans" ADD COLUMN IF NOT EXISTS "price_monthly" DOUBLE PRECISION DEFAULT 0;
ALTER TABLE "plans" ADD COLUMN IF NOT EXISTS "price_yearly" DOUBLE PRECISION DEFAULT 0;
ALTER TABLE "plans" ADD COLUMN IF NOT EXISTS "stripe_price_monthly" TEXT;
ALTER TABLE "plans" ADD COLUMN IF NOT EXISTS "stripe_price_yearly" TEXT;
ALTER TABLE "plans" ADD COLUMN IF NOT EXISTS "sort_order" BIGINT DEFAULT 0;
ALTER TABLE "plans" ADD COLUMN IF NOT EXISTS "active" BIGINT DEFAULT 1;

-- play_logs
ALTER TABLE "play_logs" ADD COLUMN IF NOT EXISTS "id" BIGINT;
ALTER TABLE "play_logs" ADD COLUMN IF NOT EXISTS "device_id" TEXT;
ALTER TABLE "play_logs" ADD COLUMN IF NOT EXISTS "content_id" TEXT;
ALTER TABLE "play_logs" ADD COLUMN IF NOT EXISTS "widget_id" TEXT;
ALTER TABLE "play_logs" ADD COLUMN IF NOT EXISTS "zone_id" TEXT;
ALTER TABLE "play_logs" ADD COLUMN IF NOT EXISTS "content_name" TEXT DEFAULT '';
ALTER TABLE "play_logs" ADD COLUMN IF NOT EXISTS "started_at" BIGINT;
ALTER TABLE "play_logs" ADD COLUMN IF NOT EXISTS "ended_at" BIGINT;
ALTER TABLE "play_logs" ADD COLUMN IF NOT EXISTS "duration_sec" BIGINT;
ALTER TABLE "play_logs" ADD COLUMN IF NOT EXISTS "completed" BIGINT DEFAULT 0;
ALTER TABLE "play_logs" ADD COLUMN IF NOT EXISTS "trigger_type" TEXT DEFAULT 'playlist';
ALTER TABLE "play_logs" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);

-- player_debug_logs
ALTER TABLE "player_debug_logs" ADD COLUMN IF NOT EXISTS "id" BIGINT;
ALTER TABLE "player_debug_logs" ADD COLUMN IF NOT EXISTS "device_id" TEXT;
ALTER TABLE "player_debug_logs" ADD COLUMN IF NOT EXISTS "ip" TEXT;
ALTER TABLE "player_debug_logs" ADD COLUMN IF NOT EXISTS "user_agent" TEXT;
ALTER TABLE "player_debug_logs" ADD COLUMN IF NOT EXISTS "url" TEXT;
ALTER TABLE "player_debug_logs" ADD COLUMN IF NOT EXISTS "error_fingerprint" TEXT;
ALTER TABLE "player_debug_logs" ADD COLUMN IF NOT EXISTS "error_data" TEXT;
ALTER TABLE "player_debug_logs" ADD COLUMN IF NOT EXISTS "context" TEXT;
ALTER TABLE "player_debug_logs" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);

-- playlist_item_schedules
ALTER TABLE "playlist_item_schedules" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "playlist_item_schedules" ADD COLUMN IF NOT EXISTS "playlist_item_id" BIGINT;
ALTER TABLE "playlist_item_schedules" ADD COLUMN IF NOT EXISTS "active_days" TEXT DEFAULT '0,1,2,3,4,5,6';
ALTER TABLE "playlist_item_schedules" ADD COLUMN IF NOT EXISTS "start_time" TEXT DEFAULT '00:00';
ALTER TABLE "playlist_item_schedules" ADD COLUMN IF NOT EXISTS "end_time" TEXT DEFAULT '24:00';
ALTER TABLE "playlist_item_schedules" ADD COLUMN IF NOT EXISTS "start_date" TEXT;
ALTER TABLE "playlist_item_schedules" ADD COLUMN IF NOT EXISTS "end_date" TEXT;
ALTER TABLE "playlist_item_schedules" ADD COLUMN IF NOT EXISTS "sort_order" BIGINT DEFAULT 0;
ALTER TABLE "playlist_item_schedules" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "playlist_item_schedules" ADD COLUMN IF NOT EXISTS "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);

-- playlist_items
ALTER TABLE "playlist_items" ADD COLUMN IF NOT EXISTS "id" BIGINT;
ALTER TABLE "playlist_items" ADD COLUMN IF NOT EXISTS "playlist_id" TEXT;
ALTER TABLE "playlist_items" ADD COLUMN IF NOT EXISTS "content_id" TEXT;
ALTER TABLE "playlist_items" ADD COLUMN IF NOT EXISTS "widget_id" TEXT;
ALTER TABLE "playlist_items" ADD COLUMN IF NOT EXISTS "zone_id" TEXT;
ALTER TABLE "playlist_items" ADD COLUMN IF NOT EXISTS "sort_order" BIGINT DEFAULT 0;
ALTER TABLE "playlist_items" ADD COLUMN IF NOT EXISTS "duration_sec" BIGINT DEFAULT 10;
ALTER TABLE "playlist_items" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "playlist_items" ADD COLUMN IF NOT EXISTS "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);

-- playlists
ALTER TABLE "playlists" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "playlists" ADD COLUMN IF NOT EXISTS "user_id" TEXT;
ALTER TABLE "playlists" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "playlists" ADD COLUMN IF NOT EXISTS "description" TEXT DEFAULT '';
ALTER TABLE "playlists" ADD COLUMN IF NOT EXISTS "is_auto_generated" BIGINT DEFAULT 0;
ALTER TABLE "playlists" ADD COLUMN IF NOT EXISTS "status" TEXT DEFAULT 'draft';
ALTER TABLE "playlists" ADD COLUMN IF NOT EXISTS "published_snapshot" TEXT;
ALTER TABLE "playlists" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "playlists" ADD COLUMN IF NOT EXISTS "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "playlists" ADD COLUMN IF NOT EXISTS "workspace_id" TEXT;

-- products
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "slug" TEXT;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "price" BIGINT;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "currency" TEXT DEFAULT 'gbp';
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "active" BIGINT DEFAULT 1;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);

-- schedules
ALTER TABLE "schedules" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "schedules" ADD COLUMN IF NOT EXISTS "user_id" TEXT;
ALTER TABLE "schedules" ADD COLUMN IF NOT EXISTS "device_id" TEXT;
ALTER TABLE "schedules" ADD COLUMN IF NOT EXISTS "group_id" TEXT;
ALTER TABLE "schedules" ADD COLUMN IF NOT EXISTS "zone_id" TEXT;
ALTER TABLE "schedules" ADD COLUMN IF NOT EXISTS "content_id" TEXT;
ALTER TABLE "schedules" ADD COLUMN IF NOT EXISTS "widget_id" TEXT;
ALTER TABLE "schedules" ADD COLUMN IF NOT EXISTS "layout_id" TEXT;
ALTER TABLE "schedules" ADD COLUMN IF NOT EXISTS "playlist_id" TEXT;
ALTER TABLE "schedules" ADD COLUMN IF NOT EXISTS "title" TEXT DEFAULT '';
ALTER TABLE "schedules" ADD COLUMN IF NOT EXISTS "start_time" TEXT;
ALTER TABLE "schedules" ADD COLUMN IF NOT EXISTS "end_time" TEXT;
ALTER TABLE "schedules" ADD COLUMN IF NOT EXISTS "timezone" TEXT DEFAULT 'UTC';
ALTER TABLE "schedules" ADD COLUMN IF NOT EXISTS "recurrence" TEXT;
ALTER TABLE "schedules" ADD COLUMN IF NOT EXISTS "recurrence_end" TEXT;
ALTER TABLE "schedules" ADD COLUMN IF NOT EXISTS "priority" BIGINT DEFAULT 0;
ALTER TABLE "schedules" ADD COLUMN IF NOT EXISTS "enabled" BIGINT DEFAULT 1;
ALTER TABLE "schedules" ADD COLUMN IF NOT EXISTS "color" TEXT DEFAULT '#3B82F6';
ALTER TABLE "schedules" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "schedules" ADD COLUMN IF NOT EXISTS "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "schedules" ADD COLUMN IF NOT EXISTS "workspace_id" TEXT;

-- schema_migrations
ALTER TABLE "schema_migrations" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "schema_migrations" ADD COLUMN IF NOT EXISTS "ran_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);

-- screenshots
ALTER TABLE "screenshots" ADD COLUMN IF NOT EXISTS "id" BIGINT;
ALTER TABLE "screenshots" ADD COLUMN IF NOT EXISTS "device_id" TEXT;
ALTER TABLE "screenshots" ADD COLUMN IF NOT EXISTS "filepath" TEXT;
ALTER TABLE "screenshots" ADD COLUMN IF NOT EXISTS "captured_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);

-- stripe_events
ALTER TABLE "stripe_events" ADD COLUMN IF NOT EXISTS "event_id" TEXT;
ALTER TABLE "stripe_events" ADD COLUMN IF NOT EXISTS "event_type" TEXT;
ALTER TABLE "stripe_events" ADD COLUMN IF NOT EXISTS "processed_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);

-- subscription_notifications
ALTER TABLE "subscription_notifications" ADD COLUMN IF NOT EXISTS "user_id" TEXT;
ALTER TABLE "subscription_notifications" ADD COLUMN IF NOT EXISTS "event_key" TEXT;
ALTER TABLE "subscription_notifications" ADD COLUMN IF NOT EXISTS "status" TEXT DEFAULT 'pending';
ALTER TABLE "subscription_notifications" ADD COLUMN IF NOT EXISTS "attempts" BIGINT DEFAULT 0;
ALTER TABLE "subscription_notifications" ADD COLUMN IF NOT EXISTS "last_error" TEXT;
ALTER TABLE "subscription_notifications" ADD COLUMN IF NOT EXISTS "sent_at" BIGINT;
ALTER TABLE "subscription_notifications" ADD COLUMN IF NOT EXISTS "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);

-- team_invites
ALTER TABLE "team_invites" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "team_invites" ADD COLUMN IF NOT EXISTS "team_id" TEXT;
ALTER TABLE "team_invites" ADD COLUMN IF NOT EXISTS "email" TEXT;
ALTER TABLE "team_invites" ADD COLUMN IF NOT EXISTS "role" TEXT DEFAULT 'viewer';
ALTER TABLE "team_invites" ADD COLUMN IF NOT EXISTS "invited_by" TEXT;
ALTER TABLE "team_invites" ADD COLUMN IF NOT EXISTS "expires_at" BIGINT;
ALTER TABLE "team_invites" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);

-- team_members
ALTER TABLE "team_members" ADD COLUMN IF NOT EXISTS "id" BIGINT;
ALTER TABLE "team_members" ADD COLUMN IF NOT EXISTS "team_id" TEXT;
ALTER TABLE "team_members" ADD COLUMN IF NOT EXISTS "user_id" TEXT;
ALTER TABLE "team_members" ADD COLUMN IF NOT EXISTS "role" TEXT DEFAULT 'viewer';
ALTER TABLE "team_members" ADD COLUMN IF NOT EXISTS "invited_by" TEXT;
ALTER TABLE "team_members" ADD COLUMN IF NOT EXISTS "joined_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);

-- teams
ALTER TABLE "teams" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "teams" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "teams" ADD COLUMN IF NOT EXISTS "owner_id" TEXT;
ALTER TABLE "teams" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);

-- totp_recovery_codes
ALTER TABLE "totp_recovery_codes" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "totp_recovery_codes" ADD COLUMN IF NOT EXISTS "user_id" TEXT;
ALTER TABLE "totp_recovery_codes" ADD COLUMN IF NOT EXISTS "code_hash" TEXT;
ALTER TABLE "totp_recovery_codes" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "totp_recovery_codes" ADD COLUMN IF NOT EXISTS "used_at" BIGINT;

-- users
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "email" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "name" TEXT DEFAULT '';
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "password_hash" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "auth_provider" TEXT DEFAULT 'local';
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "provider_id" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "avatar_url" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "role" TEXT DEFAULT 'user';
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "plan_id" TEXT DEFAULT 'free';
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "stripe_customer_id" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "stripe_subscription_id" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "subscription_status" TEXT DEFAULT 'active';
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "subscription_ends" BIGINT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "trial_started" BIGINT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "trial_ends_at" BIGINT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "trial_plan" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "past_due_grace_ends_at" BIGINT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "totp_secret_enc" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "totp_enabled" BIGINT DEFAULT 0;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "totp_last_step" BIGINT DEFAULT 0;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "email_alerts" BIGINT DEFAULT 1;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "last_login" BIGINT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "welcome_email_sent_at" BIGINT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "activation_nudge_sent_at" BIGINT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "must_change_password" BIGINT DEFAULT 0;

-- video_wall_devices
ALTER TABLE "video_wall_devices" ADD COLUMN IF NOT EXISTS "id" BIGINT;
ALTER TABLE "video_wall_devices" ADD COLUMN IF NOT EXISTS "wall_id" TEXT;
ALTER TABLE "video_wall_devices" ADD COLUMN IF NOT EXISTS "device_id" TEXT;
ALTER TABLE "video_wall_devices" ADD COLUMN IF NOT EXISTS "grid_col" BIGINT;
ALTER TABLE "video_wall_devices" ADD COLUMN IF NOT EXISTS "grid_row" BIGINT;
ALTER TABLE "video_wall_devices" ADD COLUMN IF NOT EXISTS "rotation" BIGINT DEFAULT 0;
ALTER TABLE "video_wall_devices" ADD COLUMN IF NOT EXISTS "canvas_x" DOUBLE PRECISION;
ALTER TABLE "video_wall_devices" ADD COLUMN IF NOT EXISTS "canvas_y" DOUBLE PRECISION;
ALTER TABLE "video_wall_devices" ADD COLUMN IF NOT EXISTS "canvas_width" DOUBLE PRECISION;
ALTER TABLE "video_wall_devices" ADD COLUMN IF NOT EXISTS "canvas_height" DOUBLE PRECISION;

-- video_walls
ALTER TABLE "video_walls" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "video_walls" ADD COLUMN IF NOT EXISTS "user_id" TEXT;
ALTER TABLE "video_walls" ADD COLUMN IF NOT EXISTS "team_id" TEXT;
ALTER TABLE "video_walls" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "video_walls" ADD COLUMN IF NOT EXISTS "grid_cols" BIGINT DEFAULT 2;
ALTER TABLE "video_walls" ADD COLUMN IF NOT EXISTS "grid_rows" BIGINT DEFAULT 2;
ALTER TABLE "video_walls" ADD COLUMN IF NOT EXISTS "bezel_h_mm" DOUBLE PRECISION DEFAULT 0;
ALTER TABLE "video_walls" ADD COLUMN IF NOT EXISTS "bezel_v_mm" DOUBLE PRECISION DEFAULT 0;
ALTER TABLE "video_walls" ADD COLUMN IF NOT EXISTS "screen_w_mm" DOUBLE PRECISION DEFAULT 400;
ALTER TABLE "video_walls" ADD COLUMN IF NOT EXISTS "screen_h_mm" DOUBLE PRECISION DEFAULT 225;
ALTER TABLE "video_walls" ADD COLUMN IF NOT EXISTS "sync_mode" TEXT DEFAULT 'leader';
ALTER TABLE "video_walls" ADD COLUMN IF NOT EXISTS "leader_device_id" TEXT;
ALTER TABLE "video_walls" ADD COLUMN IF NOT EXISTS "content_id" TEXT;
ALTER TABLE "video_walls" ADD COLUMN IF NOT EXISTS "playlist_id" TEXT;
ALTER TABLE "video_walls" ADD COLUMN IF NOT EXISTS "player_x" DOUBLE PRECISION;
ALTER TABLE "video_walls" ADD COLUMN IF NOT EXISTS "player_y" DOUBLE PRECISION;
ALTER TABLE "video_walls" ADD COLUMN IF NOT EXISTS "player_width" DOUBLE PRECISION;
ALTER TABLE "video_walls" ADD COLUMN IF NOT EXISTS "player_height" DOUBLE PRECISION;
ALTER TABLE "video_walls" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "video_walls" ADD COLUMN IF NOT EXISTS "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "video_walls" ADD COLUMN IF NOT EXISTS "workspace_id" TEXT;

-- white_labels
ALTER TABLE "white_labels" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "white_labels" ADD COLUMN IF NOT EXISTS "user_id" TEXT;
ALTER TABLE "white_labels" ADD COLUMN IF NOT EXISTS "brand_name" TEXT DEFAULT 'ScreenTinker';
ALTER TABLE "white_labels" ADD COLUMN IF NOT EXISTS "logo_url" TEXT;
ALTER TABLE "white_labels" ADD COLUMN IF NOT EXISTS "favicon_url" TEXT;
ALTER TABLE "white_labels" ADD COLUMN IF NOT EXISTS "primary_color" TEXT DEFAULT '#3B82F6';
ALTER TABLE "white_labels" ADD COLUMN IF NOT EXISTS "secondary_color" TEXT DEFAULT '#1E293B';
ALTER TABLE "white_labels" ADD COLUMN IF NOT EXISTS "bg_color" TEXT DEFAULT '#111827';
ALTER TABLE "white_labels" ADD COLUMN IF NOT EXISTS "custom_domain" TEXT;
ALTER TABLE "white_labels" ADD COLUMN IF NOT EXISTS "custom_css" TEXT;
ALTER TABLE "white_labels" ADD COLUMN IF NOT EXISTS "hide_branding" BIGINT DEFAULT 0;
ALTER TABLE "white_labels" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "white_labels" ADD COLUMN IF NOT EXISTS "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "white_labels" ADD COLUMN IF NOT EXISTS "workspace_id" TEXT;

-- widgets
ALTER TABLE "widgets" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "widgets" ADD COLUMN IF NOT EXISTS "user_id" TEXT;
ALTER TABLE "widgets" ADD COLUMN IF NOT EXISTS "team_id" TEXT;
ALTER TABLE "widgets" ADD COLUMN IF NOT EXISTS "widget_type" TEXT;
ALTER TABLE "widgets" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "widgets" ADD COLUMN IF NOT EXISTS "config" TEXT DEFAULT '{}';
ALTER TABLE "widgets" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "widgets" ADD COLUMN IF NOT EXISTS "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "widgets" ADD COLUMN IF NOT EXISTS "workspace_id" TEXT;

-- workspace_invites
ALTER TABLE "workspace_invites" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "workspace_invites" ADD COLUMN IF NOT EXISTS "workspace_id" TEXT;
ALTER TABLE "workspace_invites" ADD COLUMN IF NOT EXISTS "email" TEXT;
ALTER TABLE "workspace_invites" ADD COLUMN IF NOT EXISTS "role" TEXT DEFAULT 'workspace_viewer';
ALTER TABLE "workspace_invites" ADD COLUMN IF NOT EXISTS "invited_by" TEXT;
ALTER TABLE "workspace_invites" ADD COLUMN IF NOT EXISTS "expires_at" BIGINT;
ALTER TABLE "workspace_invites" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);

-- workspace_members
ALTER TABLE "workspace_members" ADD COLUMN IF NOT EXISTS "id" BIGINT;
ALTER TABLE "workspace_members" ADD COLUMN IF NOT EXISTS "workspace_id" TEXT;
ALTER TABLE "workspace_members" ADD COLUMN IF NOT EXISTS "user_id" TEXT;
ALTER TABLE "workspace_members" ADD COLUMN IF NOT EXISTS "role" TEXT DEFAULT 'workspace_viewer';
ALTER TABLE "workspace_members" ADD COLUMN IF NOT EXISTS "invited_by" TEXT;
ALTER TABLE "workspace_members" ADD COLUMN IF NOT EXISTS "joined_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);

-- workspaces
ALTER TABLE "workspaces" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "workspaces" ADD COLUMN IF NOT EXISTS "organization_id" TEXT;
ALTER TABLE "workspaces" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "workspaces" ADD COLUMN IF NOT EXISTS "slug" TEXT;
ALTER TABLE "workspaces" ADD COLUMN IF NOT EXISTS "created_by" TEXT;
ALTER TABLE "workspaces" ADD COLUMN IF NOT EXISTS "billing_type" TEXT DEFAULT 'client_billable';
ALTER TABLE "workspaces" ADD COLUMN IF NOT EXISTS "billing_notes" TEXT;
ALTER TABLE "workspaces" ADD COLUMN IF NOT EXISTS "billing_contact_email" TEXT;
ALTER TABLE "workspaces" ADD COLUMN IF NOT EXISTS "billing_contract_ref" TEXT;
ALTER TABLE "workspaces" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "workspaces" ADD COLUMN IF NOT EXISTS "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
