-- Postgres catch-up migration generated by scripts/generate-postgres-catchup.js
-- Brings a Supabase DB up to the complete runtime schema. Idempotent & safe to re-run.
-- For each table: CREATE IF NOT EXISTS (handles fully-missing tables), then
-- ADD COLUMN IF NOT EXISTS for every column (handles existing-but-incomplete tables).
-- Foreign keys are intentionally omitted so statement order never matters.
-- Paste into the Supabase SQL editor and run.

-- activity_log
CREATE TABLE IF NOT EXISTS "activity_log" (
  "id" BIGINT,
  "user_id" TEXT,
  "device_id" TEXT,
  "action" TEXT,
  "details" TEXT,
  "ip_address" TEXT,
  "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  "workspace_id" TEXT,
  "organization_id" TEXT,
  "acting_user_id" TEXT,
  "was_acting_as" BIGINT DEFAULT 0,
  PRIMARY KEY ("id")
);
ALTER TABLE "activity_log" ADD COLUMN IF NOT EXISTS "id" BIGINT;
ALTER TABLE "activity_log" ADD COLUMN IF NOT EXISTS "user_id" TEXT;
ALTER TABLE "activity_log" ADD COLUMN IF NOT EXISTS "device_id" TEXT;
ALTER TABLE "activity_log" ADD COLUMN IF NOT EXISTS "action" TEXT;
ALTER TABLE "activity_log" ADD COLUMN IF NOT EXISTS "details" TEXT;
ALTER TABLE "activity_log" ADD COLUMN IF NOT EXISTS "ip_address" TEXT;
ALTER TABLE "activity_log" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "activity_log" ADD COLUMN IF NOT EXISTS "workspace_id" TEXT;
ALTER TABLE "activity_log" ADD COLUMN IF NOT EXISTS "organization_id" TEXT;
ALTER TABLE "activity_log" ADD COLUMN IF NOT EXISTS "acting_user_id" TEXT;
ALTER TABLE "activity_log" ADD COLUMN IF NOT EXISTS "was_acting_as" BIGINT DEFAULT 0;

-- agency_notifications
CREATE TABLE IF NOT EXISTS "agency_notifications" (
  "id" BIGINT,
  "workspace_id" TEXT,
  "token_id" TEXT,
  "playlist_id" TEXT,
  "action" TEXT,
  "content_id" TEXT,
  "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  "sent_at" BIGINT,
  PRIMARY KEY ("id")
);
ALTER TABLE "agency_notifications" ADD COLUMN IF NOT EXISTS "id" BIGINT;
ALTER TABLE "agency_notifications" ADD COLUMN IF NOT EXISTS "workspace_id" TEXT;
ALTER TABLE "agency_notifications" ADD COLUMN IF NOT EXISTS "token_id" TEXT;
ALTER TABLE "agency_notifications" ADD COLUMN IF NOT EXISTS "playlist_id" TEXT;
ALTER TABLE "agency_notifications" ADD COLUMN IF NOT EXISTS "action" TEXT;
ALTER TABLE "agency_notifications" ADD COLUMN IF NOT EXISTS "content_id" TEXT;
ALTER TABLE "agency_notifications" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "agency_notifications" ADD COLUMN IF NOT EXISTS "sent_at" BIGINT;

-- ai_settings
CREATE TABLE IF NOT EXISTS "ai_settings" (
  "workspace_id" TEXT,
  "base_url" TEXT,
  "api_key_enc" TEXT,
  "model" TEXT,
  "image_base_url" TEXT,
  "image_model" TEXT,
  "image_provider" TEXT,
  "image_api_key_enc" TEXT,
  "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  PRIMARY KEY ("workspace_id")
);
ALTER TABLE "ai_settings" ADD COLUMN IF NOT EXISTS "workspace_id" TEXT;
ALTER TABLE "ai_settings" ADD COLUMN IF NOT EXISTS "base_url" TEXT;
ALTER TABLE "ai_settings" ADD COLUMN IF NOT EXISTS "api_key_enc" TEXT;
ALTER TABLE "ai_settings" ADD COLUMN IF NOT EXISTS "model" TEXT;
ALTER TABLE "ai_settings" ADD COLUMN IF NOT EXISTS "image_base_url" TEXT;
ALTER TABLE "ai_settings" ADD COLUMN IF NOT EXISTS "image_model" TEXT;
ALTER TABLE "ai_settings" ADD COLUMN IF NOT EXISTS "image_provider" TEXT;
ALTER TABLE "ai_settings" ADD COLUMN IF NOT EXISTS "image_api_key_enc" TEXT;
ALTER TABLE "ai_settings" ADD COLUMN IF NOT EXISTS "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);

-- alert_configs
CREATE TABLE IF NOT EXISTS "alert_configs" (
  "id" TEXT,
  "user_id" TEXT,
  "alert_type" TEXT,
  "enabled" BIGINT DEFAULT 1,
  "config" TEXT DEFAULT '{}',
  "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  "workspace_id" TEXT,
  PRIMARY KEY ("id")
);
ALTER TABLE "alert_configs" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "alert_configs" ADD COLUMN IF NOT EXISTS "user_id" TEXT;
ALTER TABLE "alert_configs" ADD COLUMN IF NOT EXISTS "alert_type" TEXT;
ALTER TABLE "alert_configs" ADD COLUMN IF NOT EXISTS "enabled" BIGINT DEFAULT 1;
ALTER TABLE "alert_configs" ADD COLUMN IF NOT EXISTS "config" TEXT DEFAULT '{}';
ALTER TABLE "alert_configs" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "alert_configs" ADD COLUMN IF NOT EXISTS "workspace_id" TEXT;

-- api_token_targets
CREATE TABLE IF NOT EXISTS "api_token_targets" (
  "token_id" TEXT,
  "playlist_id" TEXT,
  "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  PRIMARY KEY ("token_id", "playlist_id")
);
ALTER TABLE "api_token_targets" ADD COLUMN IF NOT EXISTS "token_id" TEXT;
ALTER TABLE "api_token_targets" ADD COLUMN IF NOT EXISTS "playlist_id" TEXT;
ALTER TABLE "api_token_targets" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);

-- api_tokens
CREATE TABLE IF NOT EXISTS "api_tokens" (
  "id" TEXT,
  "token_hash" TEXT,
  "prefix" TEXT,
  "name" TEXT,
  "user_id" TEXT,
  "workspace_id" TEXT,
  "scope" TEXT DEFAULT 'read',
  "auto_publish" BIGINT DEFAULT 0,
  "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  "last_used_at" BIGINT,
  "revoked_at" BIGINT,
  PRIMARY KEY ("id")
);
ALTER TABLE "api_tokens" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "api_tokens" ADD COLUMN IF NOT EXISTS "token_hash" TEXT;
ALTER TABLE "api_tokens" ADD COLUMN IF NOT EXISTS "prefix" TEXT;
ALTER TABLE "api_tokens" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "api_tokens" ADD COLUMN IF NOT EXISTS "user_id" TEXT;
ALTER TABLE "api_tokens" ADD COLUMN IF NOT EXISTS "workspace_id" TEXT;
ALTER TABLE "api_tokens" ADD COLUMN IF NOT EXISTS "scope" TEXT DEFAULT 'read';
ALTER TABLE "api_tokens" ADD COLUMN IF NOT EXISTS "auto_publish" BIGINT DEFAULT 0;
ALTER TABLE "api_tokens" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "api_tokens" ADD COLUMN IF NOT EXISTS "last_used_at" BIGINT;
ALTER TABLE "api_tokens" ADD COLUMN IF NOT EXISTS "revoked_at" BIGINT;

-- assignments
CREATE TABLE IF NOT EXISTS "assignments" (
  "id" BIGINT,
  "device_id" TEXT,
  "content_id" TEXT,
  "widget_id" TEXT,
  "zone_id" TEXT,
  "sort_order" BIGINT DEFAULT 0,
  "duration_sec" BIGINT DEFAULT 10,
  "schedule_start" TEXT,
  "schedule_end" TEXT,
  "schedule_days" TEXT,
  "enabled" BIGINT DEFAULT 1,
  "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  "muted" BIGINT DEFAULT 0,
  PRIMARY KEY ("id")
);
ALTER TABLE "assignments" ADD COLUMN IF NOT EXISTS "id" BIGINT;
ALTER TABLE "assignments" ADD COLUMN IF NOT EXISTS "device_id" TEXT;
ALTER TABLE "assignments" ADD COLUMN IF NOT EXISTS "content_id" TEXT;
ALTER TABLE "assignments" ADD COLUMN IF NOT EXISTS "widget_id" TEXT;
ALTER TABLE "assignments" ADD COLUMN IF NOT EXISTS "zone_id" TEXT;
ALTER TABLE "assignments" ADD COLUMN IF NOT EXISTS "sort_order" BIGINT DEFAULT 0;
ALTER TABLE "assignments" ADD COLUMN IF NOT EXISTS "duration_sec" BIGINT DEFAULT 10;
ALTER TABLE "assignments" ADD COLUMN IF NOT EXISTS "schedule_start" TEXT;
ALTER TABLE "assignments" ADD COLUMN IF NOT EXISTS "schedule_end" TEXT;
ALTER TABLE "assignments" ADD COLUMN IF NOT EXISTS "schedule_days" TEXT;
ALTER TABLE "assignments" ADD COLUMN IF NOT EXISTS "enabled" BIGINT DEFAULT 1;
ALTER TABLE "assignments" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "assignments" ADD COLUMN IF NOT EXISTS "muted" BIGINT DEFAULT 0;

-- content
CREATE TABLE IF NOT EXISTS "content" (
  "id" TEXT,
  "user_id" TEXT,
  "filename" TEXT,
  "filepath" TEXT DEFAULT '',
  "mime_type" TEXT,
  "file_size" BIGINT DEFAULT 0,
  "duration_sec" DOUBLE PRECISION,
  "thumbnail_path" TEXT,
  "width" BIGINT,
  "height" BIGINT,
  "remote_url" TEXT,
  "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  "team_id" TEXT,
  "folder" TEXT,
  "folder_id" TEXT,
  "workspace_id" TEXT,
  PRIMARY KEY ("id")
);
ALTER TABLE "content" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "content" ADD COLUMN IF NOT EXISTS "user_id" TEXT;
ALTER TABLE "content" ADD COLUMN IF NOT EXISTS "filename" TEXT;
ALTER TABLE "content" ADD COLUMN IF NOT EXISTS "filepath" TEXT DEFAULT '';
ALTER TABLE "content" ADD COLUMN IF NOT EXISTS "mime_type" TEXT;
ALTER TABLE "content" ADD COLUMN IF NOT EXISTS "file_size" BIGINT DEFAULT 0;
ALTER TABLE "content" ADD COLUMN IF NOT EXISTS "duration_sec" DOUBLE PRECISION;
ALTER TABLE "content" ADD COLUMN IF NOT EXISTS "thumbnail_path" TEXT;
ALTER TABLE "content" ADD COLUMN IF NOT EXISTS "width" BIGINT;
ALTER TABLE "content" ADD COLUMN IF NOT EXISTS "height" BIGINT;
ALTER TABLE "content" ADD COLUMN IF NOT EXISTS "remote_url" TEXT;
ALTER TABLE "content" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "content" ADD COLUMN IF NOT EXISTS "team_id" TEXT;
ALTER TABLE "content" ADD COLUMN IF NOT EXISTS "folder" TEXT;
ALTER TABLE "content" ADD COLUMN IF NOT EXISTS "folder_id" TEXT;
ALTER TABLE "content" ADD COLUMN IF NOT EXISTS "workspace_id" TEXT;

-- content_folders
CREATE TABLE IF NOT EXISTS "content_folders" (
  "id" TEXT,
  "user_id" TEXT,
  "parent_id" TEXT,
  "name" TEXT,
  "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  "workspace_id" TEXT,
  PRIMARY KEY ("id")
);
ALTER TABLE "content_folders" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "content_folders" ADD COLUMN IF NOT EXISTS "user_id" TEXT;
ALTER TABLE "content_folders" ADD COLUMN IF NOT EXISTS "parent_id" TEXT;
ALTER TABLE "content_folders" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "content_folders" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "content_folders" ADD COLUMN IF NOT EXISTS "workspace_id" TEXT;

-- device_fingerprints
CREATE TABLE IF NOT EXISTS "device_fingerprints" (
  "fingerprint" TEXT,
  "device_id" TEXT,
  "user_id" TEXT,
  "first_seen" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  "last_seen" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  PRIMARY KEY ("fingerprint")
);
ALTER TABLE "device_fingerprints" ADD COLUMN IF NOT EXISTS "fingerprint" TEXT;
ALTER TABLE "device_fingerprints" ADD COLUMN IF NOT EXISTS "device_id" TEXT;
ALTER TABLE "device_fingerprints" ADD COLUMN IF NOT EXISTS "user_id" TEXT;
ALTER TABLE "device_fingerprints" ADD COLUMN IF NOT EXISTS "first_seen" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "device_fingerprints" ADD COLUMN IF NOT EXISTS "last_seen" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);

-- device_group_members
CREATE TABLE IF NOT EXISTS "device_group_members" (
  "device_id" TEXT,
  "group_id" TEXT,
  PRIMARY KEY ("device_id", "group_id")
);
ALTER TABLE "device_group_members" ADD COLUMN IF NOT EXISTS "device_id" TEXT;
ALTER TABLE "device_group_members" ADD COLUMN IF NOT EXISTS "group_id" TEXT;

-- device_groups
CREATE TABLE IF NOT EXISTS "device_groups" (
  "id" TEXT,
  "user_id" TEXT,
  "name" TEXT,
  "color" TEXT DEFAULT '#3B82F6',
  "playlist_id" TEXT,
  "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  "workspace_id" TEXT,
  PRIMARY KEY ("id")
);
ALTER TABLE "device_groups" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "device_groups" ADD COLUMN IF NOT EXISTS "user_id" TEXT;
ALTER TABLE "device_groups" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "device_groups" ADD COLUMN IF NOT EXISTS "color" TEXT DEFAULT '#3B82F6';
ALTER TABLE "device_groups" ADD COLUMN IF NOT EXISTS "playlist_id" TEXT;
ALTER TABLE "device_groups" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "device_groups" ADD COLUMN IF NOT EXISTS "workspace_id" TEXT;

-- device_status_log
CREATE TABLE IF NOT EXISTS "device_status_log" (
  "id" BIGINT,
  "device_id" TEXT,
  "status" TEXT,
  "timestamp" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  PRIMARY KEY ("id")
);
ALTER TABLE "device_status_log" ADD COLUMN IF NOT EXISTS "id" BIGINT;
ALTER TABLE "device_status_log" ADD COLUMN IF NOT EXISTS "device_id" TEXT;
ALTER TABLE "device_status_log" ADD COLUMN IF NOT EXISTS "status" TEXT;
ALTER TABLE "device_status_log" ADD COLUMN IF NOT EXISTS "timestamp" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);

-- device_telemetry
CREATE TABLE IF NOT EXISTS "device_telemetry" (
  "id" BIGINT,
  "device_id" TEXT,
  "battery_level" BIGINT,
  "battery_charging" BIGINT DEFAULT 0,
  "storage_free_mb" BIGINT,
  "storage_total_mb" BIGINT,
  "ram_free_mb" BIGINT,
  "ram_total_mb" BIGINT,
  "cpu_usage" DOUBLE PRECISION,
  "wifi_ssid" TEXT,
  "wifi_rssi" BIGINT,
  "uptime_seconds" BIGINT,
  "reported_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  PRIMARY KEY ("id")
);
ALTER TABLE "device_telemetry" ADD COLUMN IF NOT EXISTS "id" BIGINT;
ALTER TABLE "device_telemetry" ADD COLUMN IF NOT EXISTS "device_id" TEXT;
ALTER TABLE "device_telemetry" ADD COLUMN IF NOT EXISTS "battery_level" BIGINT;
ALTER TABLE "device_telemetry" ADD COLUMN IF NOT EXISTS "battery_charging" BIGINT DEFAULT 0;
ALTER TABLE "device_telemetry" ADD COLUMN IF NOT EXISTS "storage_free_mb" BIGINT;
ALTER TABLE "device_telemetry" ADD COLUMN IF NOT EXISTS "storage_total_mb" BIGINT;
ALTER TABLE "device_telemetry" ADD COLUMN IF NOT EXISTS "ram_free_mb" BIGINT;
ALTER TABLE "device_telemetry" ADD COLUMN IF NOT EXISTS "ram_total_mb" BIGINT;
ALTER TABLE "device_telemetry" ADD COLUMN IF NOT EXISTS "cpu_usage" DOUBLE PRECISION;
ALTER TABLE "device_telemetry" ADD COLUMN IF NOT EXISTS "wifi_ssid" TEXT;
ALTER TABLE "device_telemetry" ADD COLUMN IF NOT EXISTS "wifi_rssi" BIGINT;
ALTER TABLE "device_telemetry" ADD COLUMN IF NOT EXISTS "uptime_seconds" BIGINT;
ALTER TABLE "device_telemetry" ADD COLUMN IF NOT EXISTS "reported_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);

-- devices
CREATE TABLE IF NOT EXISTS "devices" (
  "id" TEXT,
  "user_id" TEXT,
  "name" TEXT DEFAULT 'Unnamed Display',
  "pairing_code" TEXT,
  "status" TEXT DEFAULT 'offline',
  "last_heartbeat" BIGINT,
  "ip_address" TEXT,
  "android_version" TEXT,
  "app_version" TEXT,
  "screen_width" BIGINT,
  "screen_height" BIGINT,
  "playlist_id" TEXT,
  "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  "layout_id" TEXT,
  "timezone" TEXT DEFAULT 'UTC',
  "reported_timezone" TEXT,
  "reported_utc" BIGINT,
  "reported_at" BIGINT,
  "wall_id" TEXT,
  "team_id" TEXT,
  "notes" TEXT,
  "orientation" TEXT DEFAULT 'landscape',
  "default_content_id" TEXT,
  "device_token" TEXT,
  "sort_order" BIGINT DEFAULT 0,
  "workspace_id" TEXT,
  PRIMARY KEY ("id")
);
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "user_id" TEXT;
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "name" TEXT DEFAULT 'Unnamed Display';
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "pairing_code" TEXT;
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "status" TEXT DEFAULT 'offline';
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "last_heartbeat" BIGINT;
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "ip_address" TEXT;
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "android_version" TEXT;
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "app_version" TEXT;
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "screen_width" BIGINT;
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "screen_height" BIGINT;
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "playlist_id" TEXT;
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "layout_id" TEXT;
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "timezone" TEXT DEFAULT 'UTC';
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "reported_timezone" TEXT;
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "reported_utc" BIGINT;
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "reported_at" BIGINT;
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "wall_id" TEXT;
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "team_id" TEXT;
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "notes" TEXT;
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "orientation" TEXT DEFAULT 'landscape';
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "default_content_id" TEXT;
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "device_token" TEXT;
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "sort_order" BIGINT DEFAULT 0;
ALTER TABLE "devices" ADD COLUMN IF NOT EXISTS "workspace_id" TEXT;

-- hardware_orders
CREATE TABLE IF NOT EXISTS "hardware_orders" (
  "id" BIGINT,
  "order_number" TEXT,
  "user_id" TEXT,
  "stripe_session_id" TEXT,
  "stripe_payment_intent" TEXT,
  "stripe_refund_id" TEXT,
  "customer_name" TEXT DEFAULT '',
  "customer_email" TEXT,
  "customer_phone" TEXT,
  "vat_number" TEXT,
  "shipping_address_line1" TEXT DEFAULT '',
  "shipping_address_line2" TEXT,
  "city" TEXT DEFAULT '',
  "postcode" TEXT DEFAULT '',
  "country" TEXT DEFAULT '',
  "quantity" BIGINT DEFAULT 1,
  "subtotal" BIGINT DEFAULT 0,
  "tax" BIGINT DEFAULT 0,
  "total" BIGINT DEFAULT 0,
  "currency" TEXT DEFAULT 'gbp',
  "status" TEXT DEFAULT 'paid',
  "tracking_number" TEXT,
  "courier" TEXT,
  "notes" TEXT,
  "shipped_email_sent_at" BIGINT,
  "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  PRIMARY KEY ("id")
);
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "id" BIGINT;
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "order_number" TEXT;
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "user_id" TEXT;
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "stripe_session_id" TEXT;
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "stripe_payment_intent" TEXT;
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "stripe_refund_id" TEXT;
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "customer_name" TEXT DEFAULT '';
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "customer_email" TEXT;
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "customer_phone" TEXT;
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "vat_number" TEXT;
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "shipping_address_line1" TEXT DEFAULT '';
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "shipping_address_line2" TEXT;
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "city" TEXT DEFAULT '';
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "postcode" TEXT DEFAULT '';
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "country" TEXT DEFAULT '';
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "quantity" BIGINT DEFAULT 1;
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "subtotal" BIGINT DEFAULT 0;
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "tax" BIGINT DEFAULT 0;
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "total" BIGINT DEFAULT 0;
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "currency" TEXT DEFAULT 'gbp';
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "status" TEXT DEFAULT 'paid';
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "tracking_number" TEXT;
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "courier" TEXT;
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "notes" TEXT;
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "shipped_email_sent_at" BIGINT;
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "hardware_orders" ADD COLUMN IF NOT EXISTS "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);

-- kiosk_pages
CREATE TABLE IF NOT EXISTS "kiosk_pages" (
  "id" TEXT,
  "user_id" TEXT,
  "name" TEXT,
  "config" TEXT DEFAULT '{}',
  "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  "workspace_id" TEXT,
  PRIMARY KEY ("id")
);
ALTER TABLE "kiosk_pages" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "kiosk_pages" ADD COLUMN IF NOT EXISTS "user_id" TEXT;
ALTER TABLE "kiosk_pages" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "kiosk_pages" ADD COLUMN IF NOT EXISTS "config" TEXT DEFAULT '{}';
ALTER TABLE "kiosk_pages" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "kiosk_pages" ADD COLUMN IF NOT EXISTS "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "kiosk_pages" ADD COLUMN IF NOT EXISTS "workspace_id" TEXT;

-- layout_zones
CREATE TABLE IF NOT EXISTS "layout_zones" (
  "id" TEXT,
  "layout_id" TEXT,
  "name" TEXT DEFAULT 'Zone',
  "x_percent" DOUBLE PRECISION DEFAULT 0,
  "y_percent" DOUBLE PRECISION DEFAULT 0,
  "width_percent" DOUBLE PRECISION DEFAULT 100,
  "height_percent" DOUBLE PRECISION DEFAULT 100,
  "z_index" BIGINT DEFAULT 0,
  "zone_type" TEXT DEFAULT 'content',
  "fit_mode" TEXT DEFAULT 'contain',
  "background_color" TEXT DEFAULT '#000000',
  "sort_order" BIGINT DEFAULT 0,
  PRIMARY KEY ("id")
);
ALTER TABLE "layout_zones" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "layout_zones" ADD COLUMN IF NOT EXISTS "layout_id" TEXT;
ALTER TABLE "layout_zones" ADD COLUMN IF NOT EXISTS "name" TEXT DEFAULT 'Zone';
ALTER TABLE "layout_zones" ADD COLUMN IF NOT EXISTS "x_percent" DOUBLE PRECISION DEFAULT 0;
ALTER TABLE "layout_zones" ADD COLUMN IF NOT EXISTS "y_percent" DOUBLE PRECISION DEFAULT 0;
ALTER TABLE "layout_zones" ADD COLUMN IF NOT EXISTS "width_percent" DOUBLE PRECISION DEFAULT 100;
ALTER TABLE "layout_zones" ADD COLUMN IF NOT EXISTS "height_percent" DOUBLE PRECISION DEFAULT 100;
ALTER TABLE "layout_zones" ADD COLUMN IF NOT EXISTS "z_index" BIGINT DEFAULT 0;
ALTER TABLE "layout_zones" ADD COLUMN IF NOT EXISTS "zone_type" TEXT DEFAULT 'content';
ALTER TABLE "layout_zones" ADD COLUMN IF NOT EXISTS "fit_mode" TEXT DEFAULT 'contain';
ALTER TABLE "layout_zones" ADD COLUMN IF NOT EXISTS "background_color" TEXT DEFAULT '#000000';
ALTER TABLE "layout_zones" ADD COLUMN IF NOT EXISTS "sort_order" BIGINT DEFAULT 0;

-- layouts
CREATE TABLE IF NOT EXISTS "layouts" (
  "id" TEXT,
  "user_id" TEXT,
  "team_id" TEXT,
  "name" TEXT,
  "width" BIGINT DEFAULT 1920,
  "height" BIGINT DEFAULT 1080,
  "is_template" BIGINT DEFAULT 0,
  "template_category" TEXT,
  "thumbnail_data" TEXT,
  "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  "workspace_id" TEXT,
  PRIMARY KEY ("id")
);
ALTER TABLE "layouts" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "layouts" ADD COLUMN IF NOT EXISTS "user_id" TEXT;
ALTER TABLE "layouts" ADD COLUMN IF NOT EXISTS "team_id" TEXT;
ALTER TABLE "layouts" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "layouts" ADD COLUMN IF NOT EXISTS "width" BIGINT DEFAULT 1920;
ALTER TABLE "layouts" ADD COLUMN IF NOT EXISTS "height" BIGINT DEFAULT 1080;
ALTER TABLE "layouts" ADD COLUMN IF NOT EXISTS "is_template" BIGINT DEFAULT 0;
ALTER TABLE "layouts" ADD COLUMN IF NOT EXISTS "template_category" TEXT;
ALTER TABLE "layouts" ADD COLUMN IF NOT EXISTS "thumbnail_data" TEXT;
ALTER TABLE "layouts" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "layouts" ADD COLUMN IF NOT EXISTS "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "layouts" ADD COLUMN IF NOT EXISTS "workspace_id" TEXT;

-- order_items
CREATE TABLE IF NOT EXISTS "order_items" (
  "id" BIGINT,
  "order_id" BIGINT,
  "product_id" TEXT,
  "quantity" BIGINT DEFAULT 1,
  "unit_price" BIGINT,
  "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  PRIMARY KEY ("id")
);
ALTER TABLE "order_items" ADD COLUMN IF NOT EXISTS "id" BIGINT;
ALTER TABLE "order_items" ADD COLUMN IF NOT EXISTS "order_id" BIGINT;
ALTER TABLE "order_items" ADD COLUMN IF NOT EXISTS "product_id" TEXT;
ALTER TABLE "order_items" ADD COLUMN IF NOT EXISTS "quantity" BIGINT DEFAULT 1;
ALTER TABLE "order_items" ADD COLUMN IF NOT EXISTS "unit_price" BIGINT;
ALTER TABLE "order_items" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);

-- organization_members
CREATE TABLE IF NOT EXISTS "organization_members" (
  "id" BIGINT,
  "organization_id" TEXT,
  "user_id" TEXT,
  "role" TEXT DEFAULT 'org_admin',
  "invited_by" TEXT,
  "joined_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  PRIMARY KEY ("id")
);
ALTER TABLE "organization_members" ADD COLUMN IF NOT EXISTS "id" BIGINT;
ALTER TABLE "organization_members" ADD COLUMN IF NOT EXISTS "organization_id" TEXT;
ALTER TABLE "organization_members" ADD COLUMN IF NOT EXISTS "user_id" TEXT;
ALTER TABLE "organization_members" ADD COLUMN IF NOT EXISTS "role" TEXT DEFAULT 'org_admin';
ALTER TABLE "organization_members" ADD COLUMN IF NOT EXISTS "invited_by" TEXT;
ALTER TABLE "organization_members" ADD COLUMN IF NOT EXISTS "joined_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);

-- organizations
CREATE TABLE IF NOT EXISTS "organizations" (
  "id" TEXT,
  "name" TEXT,
  "slug" TEXT,
  "owner_user_id" TEXT,
  "plan_id" TEXT DEFAULT 'free',
  "stripe_customer_id" TEXT,
  "stripe_subscription_id" TEXT,
  "subscription_status" TEXT DEFAULT 'active',
  "subscription_ends" BIGINT,
  "grace_period_ends" BIGINT,
  "locked_at" BIGINT,
  "default_brand_name" TEXT,
  "default_logo_url" TEXT,
  "default_primary_color" TEXT,
  "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  PRIMARY KEY ("id")
);
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "slug" TEXT;
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "owner_user_id" TEXT;
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "plan_id" TEXT DEFAULT 'free';
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "stripe_customer_id" TEXT;
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "stripe_subscription_id" TEXT;
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "subscription_status" TEXT DEFAULT 'active';
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "subscription_ends" BIGINT;
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "grace_period_ends" BIGINT;
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "locked_at" BIGINT;
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "default_brand_name" TEXT;
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "default_logo_url" TEXT;
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "default_primary_color" TEXT;
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "organizations" ADD COLUMN IF NOT EXISTS "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);

-- plans
CREATE TABLE IF NOT EXISTS "plans" (
  "id" TEXT,
  "name" TEXT,
  "display_name" TEXT,
  "max_devices" BIGINT DEFAULT 2,
  "max_storage_mb" BIGINT DEFAULT 500,
  "remote_control" BIGINT DEFAULT 0,
  "remote_url" BIGINT DEFAULT 0,
  "priority_support" BIGINT DEFAULT 0,
  "price_monthly" DOUBLE PRECISION DEFAULT 0,
  "price_yearly" DOUBLE PRECISION DEFAULT 0,
  "stripe_price_monthly" TEXT,
  "stripe_price_yearly" TEXT,
  "sort_order" BIGINT DEFAULT 0,
  "active" BIGINT DEFAULT 1,
  PRIMARY KEY ("id")
);
ALTER TABLE "plans" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "plans" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "plans" ADD COLUMN IF NOT EXISTS "display_name" TEXT;
ALTER TABLE "plans" ADD COLUMN IF NOT EXISTS "max_devices" BIGINT DEFAULT 2;
ALTER TABLE "plans" ADD COLUMN IF NOT EXISTS "max_storage_mb" BIGINT DEFAULT 500;
ALTER TABLE "plans" ADD COLUMN IF NOT EXISTS "remote_control" BIGINT DEFAULT 0;
ALTER TABLE "plans" ADD COLUMN IF NOT EXISTS "remote_url" BIGINT DEFAULT 0;
ALTER TABLE "plans" ADD COLUMN IF NOT EXISTS "priority_support" BIGINT DEFAULT 0;
ALTER TABLE "plans" ADD COLUMN IF NOT EXISTS "price_monthly" DOUBLE PRECISION DEFAULT 0;
ALTER TABLE "plans" ADD COLUMN IF NOT EXISTS "price_yearly" DOUBLE PRECISION DEFAULT 0;
ALTER TABLE "plans" ADD COLUMN IF NOT EXISTS "stripe_price_monthly" TEXT;
ALTER TABLE "plans" ADD COLUMN IF NOT EXISTS "stripe_price_yearly" TEXT;
ALTER TABLE "plans" ADD COLUMN IF NOT EXISTS "sort_order" BIGINT DEFAULT 0;
ALTER TABLE "plans" ADD COLUMN IF NOT EXISTS "active" BIGINT DEFAULT 1;

-- play_logs
CREATE TABLE IF NOT EXISTS "play_logs" (
  "id" BIGINT,
  "device_id" TEXT,
  "content_id" TEXT,
  "widget_id" TEXT,
  "zone_id" TEXT,
  "content_name" TEXT DEFAULT '',
  "started_at" BIGINT,
  "ended_at" BIGINT,
  "duration_sec" BIGINT,
  "completed" BIGINT DEFAULT 0,
  "trigger_type" TEXT DEFAULT 'playlist',
  "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  PRIMARY KEY ("id")
);
ALTER TABLE "play_logs" ADD COLUMN IF NOT EXISTS "id" BIGINT;
ALTER TABLE "play_logs" ADD COLUMN IF NOT EXISTS "device_id" TEXT;
ALTER TABLE "play_logs" ADD COLUMN IF NOT EXISTS "content_id" TEXT;
ALTER TABLE "play_logs" ADD COLUMN IF NOT EXISTS "widget_id" TEXT;
ALTER TABLE "play_logs" ADD COLUMN IF NOT EXISTS "zone_id" TEXT;
ALTER TABLE "play_logs" ADD COLUMN IF NOT EXISTS "content_name" TEXT DEFAULT '';
ALTER TABLE "play_logs" ADD COLUMN IF NOT EXISTS "started_at" BIGINT;
ALTER TABLE "play_logs" ADD COLUMN IF NOT EXISTS "ended_at" BIGINT;
ALTER TABLE "play_logs" ADD COLUMN IF NOT EXISTS "duration_sec" BIGINT;
ALTER TABLE "play_logs" ADD COLUMN IF NOT EXISTS "completed" BIGINT DEFAULT 0;
ALTER TABLE "play_logs" ADD COLUMN IF NOT EXISTS "trigger_type" TEXT DEFAULT 'playlist';
ALTER TABLE "play_logs" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);

-- player_debug_logs
CREATE TABLE IF NOT EXISTS "player_debug_logs" (
  "id" BIGINT,
  "device_id" TEXT,
  "ip" TEXT,
  "user_agent" TEXT,
  "url" TEXT,
  "error_fingerprint" TEXT,
  "error_data" TEXT,
  "context" TEXT,
  "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  PRIMARY KEY ("id")
);
ALTER TABLE "player_debug_logs" ADD COLUMN IF NOT EXISTS "id" BIGINT;
ALTER TABLE "player_debug_logs" ADD COLUMN IF NOT EXISTS "device_id" TEXT;
ALTER TABLE "player_debug_logs" ADD COLUMN IF NOT EXISTS "ip" TEXT;
ALTER TABLE "player_debug_logs" ADD COLUMN IF NOT EXISTS "user_agent" TEXT;
ALTER TABLE "player_debug_logs" ADD COLUMN IF NOT EXISTS "url" TEXT;
ALTER TABLE "player_debug_logs" ADD COLUMN IF NOT EXISTS "error_fingerprint" TEXT;
ALTER TABLE "player_debug_logs" ADD COLUMN IF NOT EXISTS "error_data" TEXT;
ALTER TABLE "player_debug_logs" ADD COLUMN IF NOT EXISTS "context" TEXT;
ALTER TABLE "player_debug_logs" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);

-- playlist_item_schedules
CREATE TABLE IF NOT EXISTS "playlist_item_schedules" (
  "id" TEXT,
  "playlist_item_id" BIGINT,
  "active_days" TEXT DEFAULT '0,1,2,3,4,5,6',
  "start_time" TEXT DEFAULT '00:00',
  "end_time" TEXT DEFAULT '24:00',
  "start_date" TEXT,
  "end_date" TEXT,
  "sort_order" BIGINT DEFAULT 0,
  "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  PRIMARY KEY ("id")
);
ALTER TABLE "playlist_item_schedules" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "playlist_item_schedules" ADD COLUMN IF NOT EXISTS "playlist_item_id" BIGINT;
ALTER TABLE "playlist_item_schedules" ADD COLUMN IF NOT EXISTS "active_days" TEXT DEFAULT '0,1,2,3,4,5,6';
ALTER TABLE "playlist_item_schedules" ADD COLUMN IF NOT EXISTS "start_time" TEXT DEFAULT '00:00';
ALTER TABLE "playlist_item_schedules" ADD COLUMN IF NOT EXISTS "end_time" TEXT DEFAULT '24:00';
ALTER TABLE "playlist_item_schedules" ADD COLUMN IF NOT EXISTS "start_date" TEXT;
ALTER TABLE "playlist_item_schedules" ADD COLUMN IF NOT EXISTS "end_date" TEXT;
ALTER TABLE "playlist_item_schedules" ADD COLUMN IF NOT EXISTS "sort_order" BIGINT DEFAULT 0;
ALTER TABLE "playlist_item_schedules" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "playlist_item_schedules" ADD COLUMN IF NOT EXISTS "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);

-- playlist_items
CREATE TABLE IF NOT EXISTS "playlist_items" (
  "id" BIGINT,
  "playlist_id" TEXT,
  "content_id" TEXT,
  "widget_id" TEXT,
  "zone_id" TEXT,
  "sort_order" BIGINT DEFAULT 0,
  "duration_sec" BIGINT DEFAULT 10,
  "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  PRIMARY KEY ("id")
);
ALTER TABLE "playlist_items" ADD COLUMN IF NOT EXISTS "id" BIGINT;
ALTER TABLE "playlist_items" ADD COLUMN IF NOT EXISTS "playlist_id" TEXT;
ALTER TABLE "playlist_items" ADD COLUMN IF NOT EXISTS "content_id" TEXT;
ALTER TABLE "playlist_items" ADD COLUMN IF NOT EXISTS "widget_id" TEXT;
ALTER TABLE "playlist_items" ADD COLUMN IF NOT EXISTS "zone_id" TEXT;
ALTER TABLE "playlist_items" ADD COLUMN IF NOT EXISTS "sort_order" BIGINT DEFAULT 0;
ALTER TABLE "playlist_items" ADD COLUMN IF NOT EXISTS "duration_sec" BIGINT DEFAULT 10;
ALTER TABLE "playlist_items" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "playlist_items" ADD COLUMN IF NOT EXISTS "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);

-- playlists
CREATE TABLE IF NOT EXISTS "playlists" (
  "id" TEXT,
  "user_id" TEXT,
  "name" TEXT,
  "description" TEXT DEFAULT '',
  "is_auto_generated" BIGINT DEFAULT 0,
  "status" TEXT DEFAULT 'draft',
  "published_snapshot" TEXT,
  "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  "workspace_id" TEXT,
  PRIMARY KEY ("id")
);
ALTER TABLE "playlists" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "playlists" ADD COLUMN IF NOT EXISTS "user_id" TEXT;
ALTER TABLE "playlists" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "playlists" ADD COLUMN IF NOT EXISTS "description" TEXT DEFAULT '';
ALTER TABLE "playlists" ADD COLUMN IF NOT EXISTS "is_auto_generated" BIGINT DEFAULT 0;
ALTER TABLE "playlists" ADD COLUMN IF NOT EXISTS "status" TEXT DEFAULT 'draft';
ALTER TABLE "playlists" ADD COLUMN IF NOT EXISTS "published_snapshot" TEXT;
ALTER TABLE "playlists" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "playlists" ADD COLUMN IF NOT EXISTS "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "playlists" ADD COLUMN IF NOT EXISTS "workspace_id" TEXT;

-- products
CREATE TABLE IF NOT EXISTS "products" (
  "id" TEXT,
  "name" TEXT,
  "slug" TEXT,
  "price" BIGINT,
  "currency" TEXT DEFAULT 'gbp',
  "active" BIGINT DEFAULT 1,
  "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  PRIMARY KEY ("id")
);
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "slug" TEXT;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "price" BIGINT;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "currency" TEXT DEFAULT 'gbp';
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "active" BIGINT DEFAULT 1;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);

-- schedules
CREATE TABLE IF NOT EXISTS "schedules" (
  "id" TEXT,
  "user_id" TEXT,
  "device_id" TEXT,
  "group_id" TEXT,
  "zone_id" TEXT,
  "content_id" TEXT,
  "widget_id" TEXT,
  "layout_id" TEXT,
  "playlist_id" TEXT,
  "title" TEXT DEFAULT '',
  "start_time" TEXT,
  "end_time" TEXT,
  "timezone" TEXT DEFAULT 'UTC',
  "recurrence" TEXT,
  "recurrence_end" TEXT,
  "priority" BIGINT DEFAULT 0,
  "enabled" BIGINT DEFAULT 1,
  "color" TEXT DEFAULT '#3B82F6',
  "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  "workspace_id" TEXT,
  PRIMARY KEY ("id")
);
ALTER TABLE "schedules" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "schedules" ADD COLUMN IF NOT EXISTS "user_id" TEXT;
ALTER TABLE "schedules" ADD COLUMN IF NOT EXISTS "device_id" TEXT;
ALTER TABLE "schedules" ADD COLUMN IF NOT EXISTS "group_id" TEXT;
ALTER TABLE "schedules" ADD COLUMN IF NOT EXISTS "zone_id" TEXT;
ALTER TABLE "schedules" ADD COLUMN IF NOT EXISTS "content_id" TEXT;
ALTER TABLE "schedules" ADD COLUMN IF NOT EXISTS "widget_id" TEXT;
ALTER TABLE "schedules" ADD COLUMN IF NOT EXISTS "layout_id" TEXT;
ALTER TABLE "schedules" ADD COLUMN IF NOT EXISTS "playlist_id" TEXT;
ALTER TABLE "schedules" ADD COLUMN IF NOT EXISTS "title" TEXT DEFAULT '';
ALTER TABLE "schedules" ADD COLUMN IF NOT EXISTS "start_time" TEXT;
ALTER TABLE "schedules" ADD COLUMN IF NOT EXISTS "end_time" TEXT;
ALTER TABLE "schedules" ADD COLUMN IF NOT EXISTS "timezone" TEXT DEFAULT 'UTC';
ALTER TABLE "schedules" ADD COLUMN IF NOT EXISTS "recurrence" TEXT;
ALTER TABLE "schedules" ADD COLUMN IF NOT EXISTS "recurrence_end" TEXT;
ALTER TABLE "schedules" ADD COLUMN IF NOT EXISTS "priority" BIGINT DEFAULT 0;
ALTER TABLE "schedules" ADD COLUMN IF NOT EXISTS "enabled" BIGINT DEFAULT 1;
ALTER TABLE "schedules" ADD COLUMN IF NOT EXISTS "color" TEXT DEFAULT '#3B82F6';
ALTER TABLE "schedules" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "schedules" ADD COLUMN IF NOT EXISTS "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "schedules" ADD COLUMN IF NOT EXISTS "workspace_id" TEXT;

-- schema_migrations
CREATE TABLE IF NOT EXISTS "schema_migrations" (
  "id" TEXT,
  "ran_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  PRIMARY KEY ("id")
);
ALTER TABLE "schema_migrations" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "schema_migrations" ADD COLUMN IF NOT EXISTS "ran_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);

-- screenshots
CREATE TABLE IF NOT EXISTS "screenshots" (
  "id" BIGINT,
  "device_id" TEXT,
  "filepath" TEXT,
  "captured_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  PRIMARY KEY ("id")
);
ALTER TABLE "screenshots" ADD COLUMN IF NOT EXISTS "id" BIGINT;
ALTER TABLE "screenshots" ADD COLUMN IF NOT EXISTS "device_id" TEXT;
ALTER TABLE "screenshots" ADD COLUMN IF NOT EXISTS "filepath" TEXT;
ALTER TABLE "screenshots" ADD COLUMN IF NOT EXISTS "captured_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);

-- stripe_events
CREATE TABLE IF NOT EXISTS "stripe_events" (
  "event_id" TEXT,
  "event_type" TEXT,
  "processed_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  PRIMARY KEY ("event_id")
);
ALTER TABLE "stripe_events" ADD COLUMN IF NOT EXISTS "event_id" TEXT;
ALTER TABLE "stripe_events" ADD COLUMN IF NOT EXISTS "event_type" TEXT;
ALTER TABLE "stripe_events" ADD COLUMN IF NOT EXISTS "processed_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);

-- subscription_notifications
CREATE TABLE IF NOT EXISTS "subscription_notifications" (
  "user_id" TEXT,
  "event_key" TEXT,
  "status" TEXT DEFAULT 'pending',
  "attempts" BIGINT DEFAULT 0,
  "last_error" TEXT,
  "sent_at" BIGINT,
  "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  PRIMARY KEY ("user_id", "event_key")
);
ALTER TABLE "subscription_notifications" ADD COLUMN IF NOT EXISTS "user_id" TEXT;
ALTER TABLE "subscription_notifications" ADD COLUMN IF NOT EXISTS "event_key" TEXT;
ALTER TABLE "subscription_notifications" ADD COLUMN IF NOT EXISTS "status" TEXT DEFAULT 'pending';
ALTER TABLE "subscription_notifications" ADD COLUMN IF NOT EXISTS "attempts" BIGINT DEFAULT 0;
ALTER TABLE "subscription_notifications" ADD COLUMN IF NOT EXISTS "last_error" TEXT;
ALTER TABLE "subscription_notifications" ADD COLUMN IF NOT EXISTS "sent_at" BIGINT;
ALTER TABLE "subscription_notifications" ADD COLUMN IF NOT EXISTS "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);

-- team_invites
CREATE TABLE IF NOT EXISTS "team_invites" (
  "id" TEXT,
  "team_id" TEXT,
  "email" TEXT,
  "role" TEXT DEFAULT 'viewer',
  "invited_by" TEXT,
  "expires_at" BIGINT,
  "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  PRIMARY KEY ("id")
);
ALTER TABLE "team_invites" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "team_invites" ADD COLUMN IF NOT EXISTS "team_id" TEXT;
ALTER TABLE "team_invites" ADD COLUMN IF NOT EXISTS "email" TEXT;
ALTER TABLE "team_invites" ADD COLUMN IF NOT EXISTS "role" TEXT DEFAULT 'viewer';
ALTER TABLE "team_invites" ADD COLUMN IF NOT EXISTS "invited_by" TEXT;
ALTER TABLE "team_invites" ADD COLUMN IF NOT EXISTS "expires_at" BIGINT;
ALTER TABLE "team_invites" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);

-- team_members
CREATE TABLE IF NOT EXISTS "team_members" (
  "id" BIGINT,
  "team_id" TEXT,
  "user_id" TEXT,
  "role" TEXT DEFAULT 'viewer',
  "invited_by" TEXT,
  "joined_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  PRIMARY KEY ("id")
);
ALTER TABLE "team_members" ADD COLUMN IF NOT EXISTS "id" BIGINT;
ALTER TABLE "team_members" ADD COLUMN IF NOT EXISTS "team_id" TEXT;
ALTER TABLE "team_members" ADD COLUMN IF NOT EXISTS "user_id" TEXT;
ALTER TABLE "team_members" ADD COLUMN IF NOT EXISTS "role" TEXT DEFAULT 'viewer';
ALTER TABLE "team_members" ADD COLUMN IF NOT EXISTS "invited_by" TEXT;
ALTER TABLE "team_members" ADD COLUMN IF NOT EXISTS "joined_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);

-- teams
CREATE TABLE IF NOT EXISTS "teams" (
  "id" TEXT,
  "name" TEXT,
  "owner_id" TEXT,
  "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  PRIMARY KEY ("id")
);
ALTER TABLE "teams" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "teams" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "teams" ADD COLUMN IF NOT EXISTS "owner_id" TEXT;
ALTER TABLE "teams" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);

-- totp_recovery_codes
CREATE TABLE IF NOT EXISTS "totp_recovery_codes" (
  "id" TEXT,
  "user_id" TEXT,
  "code_hash" TEXT,
  "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  "used_at" BIGINT,
  PRIMARY KEY ("id")
);
ALTER TABLE "totp_recovery_codes" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "totp_recovery_codes" ADD COLUMN IF NOT EXISTS "user_id" TEXT;
ALTER TABLE "totp_recovery_codes" ADD COLUMN IF NOT EXISTS "code_hash" TEXT;
ALTER TABLE "totp_recovery_codes" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "totp_recovery_codes" ADD COLUMN IF NOT EXISTS "used_at" BIGINT;

-- users
CREATE TABLE IF NOT EXISTS "users" (
  "id" TEXT,
  "email" TEXT,
  "name" TEXT DEFAULT '',
  "password_hash" TEXT,
  "auth_provider" TEXT DEFAULT 'local',
  "provider_id" TEXT,
  "avatar_url" TEXT,
  "role" TEXT DEFAULT 'user',
  "plan_id" TEXT DEFAULT 'free',
  "stripe_customer_id" TEXT,
  "stripe_subscription_id" TEXT,
  "subscription_status" TEXT DEFAULT 'active',
  "subscription_ends" BIGINT,
  "trial_started" BIGINT,
  "trial_ends_at" BIGINT,
  "trial_plan" TEXT,
  "past_due_grace_ends_at" BIGINT,
  "totp_secret_enc" TEXT,
  "totp_enabled" BIGINT DEFAULT 0,
  "totp_last_step" BIGINT DEFAULT 0,
  "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  "email_alerts" BIGINT DEFAULT 1,
  "last_login" BIGINT,
  "welcome_email_sent_at" BIGINT,
  "activation_nudge_sent_at" BIGINT,
  "must_change_password" BIGINT DEFAULT 0,
  PRIMARY KEY ("id")
);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "email" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "name" TEXT DEFAULT '';
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "password_hash" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "auth_provider" TEXT DEFAULT 'local';
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "provider_id" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "avatar_url" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "role" TEXT DEFAULT 'user';
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "plan_id" TEXT DEFAULT 'free';
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "stripe_customer_id" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "stripe_subscription_id" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "subscription_status" TEXT DEFAULT 'active';
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "subscription_ends" BIGINT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "trial_started" BIGINT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "trial_ends_at" BIGINT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "trial_plan" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "past_due_grace_ends_at" BIGINT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "totp_secret_enc" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "totp_enabled" BIGINT DEFAULT 0;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "totp_last_step" BIGINT DEFAULT 0;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "email_alerts" BIGINT DEFAULT 1;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "last_login" BIGINT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "welcome_email_sent_at" BIGINT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "activation_nudge_sent_at" BIGINT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "must_change_password" BIGINT DEFAULT 0;

-- video_wall_devices
CREATE TABLE IF NOT EXISTS "video_wall_devices" (
  "id" BIGINT,
  "wall_id" TEXT,
  "device_id" TEXT,
  "grid_col" BIGINT,
  "grid_row" BIGINT,
  "rotation" BIGINT DEFAULT 0,
  "canvas_x" DOUBLE PRECISION,
  "canvas_y" DOUBLE PRECISION,
  "canvas_width" DOUBLE PRECISION,
  "canvas_height" DOUBLE PRECISION,
  PRIMARY KEY ("id")
);
ALTER TABLE "video_wall_devices" ADD COLUMN IF NOT EXISTS "id" BIGINT;
ALTER TABLE "video_wall_devices" ADD COLUMN IF NOT EXISTS "wall_id" TEXT;
ALTER TABLE "video_wall_devices" ADD COLUMN IF NOT EXISTS "device_id" TEXT;
ALTER TABLE "video_wall_devices" ADD COLUMN IF NOT EXISTS "grid_col" BIGINT;
ALTER TABLE "video_wall_devices" ADD COLUMN IF NOT EXISTS "grid_row" BIGINT;
ALTER TABLE "video_wall_devices" ADD COLUMN IF NOT EXISTS "rotation" BIGINT DEFAULT 0;
ALTER TABLE "video_wall_devices" ADD COLUMN IF NOT EXISTS "canvas_x" DOUBLE PRECISION;
ALTER TABLE "video_wall_devices" ADD COLUMN IF NOT EXISTS "canvas_y" DOUBLE PRECISION;
ALTER TABLE "video_wall_devices" ADD COLUMN IF NOT EXISTS "canvas_width" DOUBLE PRECISION;
ALTER TABLE "video_wall_devices" ADD COLUMN IF NOT EXISTS "canvas_height" DOUBLE PRECISION;

-- video_walls
CREATE TABLE IF NOT EXISTS "video_walls" (
  "id" TEXT,
  "user_id" TEXT,
  "team_id" TEXT,
  "name" TEXT,
  "grid_cols" BIGINT DEFAULT 2,
  "grid_rows" BIGINT DEFAULT 2,
  "bezel_h_mm" DOUBLE PRECISION DEFAULT 0,
  "bezel_v_mm" DOUBLE PRECISION DEFAULT 0,
  "screen_w_mm" DOUBLE PRECISION DEFAULT 400,
  "screen_h_mm" DOUBLE PRECISION DEFAULT 225,
  "sync_mode" TEXT DEFAULT 'leader',
  "leader_device_id" TEXT,
  "content_id" TEXT,
  "playlist_id" TEXT,
  "player_x" DOUBLE PRECISION,
  "player_y" DOUBLE PRECISION,
  "player_width" DOUBLE PRECISION,
  "player_height" DOUBLE PRECISION,
  "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  "workspace_id" TEXT,
  PRIMARY KEY ("id")
);
ALTER TABLE "video_walls" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "video_walls" ADD COLUMN IF NOT EXISTS "user_id" TEXT;
ALTER TABLE "video_walls" ADD COLUMN IF NOT EXISTS "team_id" TEXT;
ALTER TABLE "video_walls" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "video_walls" ADD COLUMN IF NOT EXISTS "grid_cols" BIGINT DEFAULT 2;
ALTER TABLE "video_walls" ADD COLUMN IF NOT EXISTS "grid_rows" BIGINT DEFAULT 2;
ALTER TABLE "video_walls" ADD COLUMN IF NOT EXISTS "bezel_h_mm" DOUBLE PRECISION DEFAULT 0;
ALTER TABLE "video_walls" ADD COLUMN IF NOT EXISTS "bezel_v_mm" DOUBLE PRECISION DEFAULT 0;
ALTER TABLE "video_walls" ADD COLUMN IF NOT EXISTS "screen_w_mm" DOUBLE PRECISION DEFAULT 400;
ALTER TABLE "video_walls" ADD COLUMN IF NOT EXISTS "screen_h_mm" DOUBLE PRECISION DEFAULT 225;
ALTER TABLE "video_walls" ADD COLUMN IF NOT EXISTS "sync_mode" TEXT DEFAULT 'leader';
ALTER TABLE "video_walls" ADD COLUMN IF NOT EXISTS "leader_device_id" TEXT;
ALTER TABLE "video_walls" ADD COLUMN IF NOT EXISTS "content_id" TEXT;
ALTER TABLE "video_walls" ADD COLUMN IF NOT EXISTS "playlist_id" TEXT;
ALTER TABLE "video_walls" ADD COLUMN IF NOT EXISTS "player_x" DOUBLE PRECISION;
ALTER TABLE "video_walls" ADD COLUMN IF NOT EXISTS "player_y" DOUBLE PRECISION;
ALTER TABLE "video_walls" ADD COLUMN IF NOT EXISTS "player_width" DOUBLE PRECISION;
ALTER TABLE "video_walls" ADD COLUMN IF NOT EXISTS "player_height" DOUBLE PRECISION;
ALTER TABLE "video_walls" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "video_walls" ADD COLUMN IF NOT EXISTS "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "video_walls" ADD COLUMN IF NOT EXISTS "workspace_id" TEXT;

-- white_labels
CREATE TABLE IF NOT EXISTS "white_labels" (
  "id" TEXT,
  "user_id" TEXT,
  "brand_name" TEXT DEFAULT 'ScreenTinker',
  "logo_url" TEXT,
  "favicon_url" TEXT,
  "primary_color" TEXT DEFAULT '#3B82F6',
  "secondary_color" TEXT DEFAULT '#1E293B',
  "bg_color" TEXT DEFAULT '#111827',
  "custom_domain" TEXT,
  "custom_css" TEXT,
  "hide_branding" BIGINT DEFAULT 0,
  "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  "workspace_id" TEXT,
  PRIMARY KEY ("id")
);
ALTER TABLE "white_labels" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "white_labels" ADD COLUMN IF NOT EXISTS "user_id" TEXT;
ALTER TABLE "white_labels" ADD COLUMN IF NOT EXISTS "brand_name" TEXT DEFAULT 'ScreenTinker';
ALTER TABLE "white_labels" ADD COLUMN IF NOT EXISTS "logo_url" TEXT;
ALTER TABLE "white_labels" ADD COLUMN IF NOT EXISTS "favicon_url" TEXT;
ALTER TABLE "white_labels" ADD COLUMN IF NOT EXISTS "primary_color" TEXT DEFAULT '#3B82F6';
ALTER TABLE "white_labels" ADD COLUMN IF NOT EXISTS "secondary_color" TEXT DEFAULT '#1E293B';
ALTER TABLE "white_labels" ADD COLUMN IF NOT EXISTS "bg_color" TEXT DEFAULT '#111827';
ALTER TABLE "white_labels" ADD COLUMN IF NOT EXISTS "custom_domain" TEXT;
ALTER TABLE "white_labels" ADD COLUMN IF NOT EXISTS "custom_css" TEXT;
ALTER TABLE "white_labels" ADD COLUMN IF NOT EXISTS "hide_branding" BIGINT DEFAULT 0;
ALTER TABLE "white_labels" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "white_labels" ADD COLUMN IF NOT EXISTS "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "white_labels" ADD COLUMN IF NOT EXISTS "workspace_id" TEXT;

-- widgets
CREATE TABLE IF NOT EXISTS "widgets" (
  "id" TEXT,
  "user_id" TEXT,
  "team_id" TEXT,
  "widget_type" TEXT,
  "name" TEXT,
  "config" TEXT DEFAULT '{}',
  "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  "workspace_id" TEXT,
  PRIMARY KEY ("id")
);
ALTER TABLE "widgets" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "widgets" ADD COLUMN IF NOT EXISTS "user_id" TEXT;
ALTER TABLE "widgets" ADD COLUMN IF NOT EXISTS "team_id" TEXT;
ALTER TABLE "widgets" ADD COLUMN IF NOT EXISTS "widget_type" TEXT;
ALTER TABLE "widgets" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "widgets" ADD COLUMN IF NOT EXISTS "config" TEXT DEFAULT '{}';
ALTER TABLE "widgets" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "widgets" ADD COLUMN IF NOT EXISTS "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "widgets" ADD COLUMN IF NOT EXISTS "workspace_id" TEXT;

-- workspace_invites
CREATE TABLE IF NOT EXISTS "workspace_invites" (
  "id" TEXT,
  "workspace_id" TEXT,
  "email" TEXT,
  "role" TEXT DEFAULT 'workspace_viewer',
  "invited_by" TEXT,
  "expires_at" BIGINT,
  "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  PRIMARY KEY ("id")
);
ALTER TABLE "workspace_invites" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "workspace_invites" ADD COLUMN IF NOT EXISTS "workspace_id" TEXT;
ALTER TABLE "workspace_invites" ADD COLUMN IF NOT EXISTS "email" TEXT;
ALTER TABLE "workspace_invites" ADD COLUMN IF NOT EXISTS "role" TEXT DEFAULT 'workspace_viewer';
ALTER TABLE "workspace_invites" ADD COLUMN IF NOT EXISTS "invited_by" TEXT;
ALTER TABLE "workspace_invites" ADD COLUMN IF NOT EXISTS "expires_at" BIGINT;
ALTER TABLE "workspace_invites" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);

-- workspace_members
CREATE TABLE IF NOT EXISTS "workspace_members" (
  "id" BIGINT,
  "workspace_id" TEXT,
  "user_id" TEXT,
  "role" TEXT DEFAULT 'workspace_viewer',
  "invited_by" TEXT,
  "joined_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  PRIMARY KEY ("id")
);
ALTER TABLE "workspace_members" ADD COLUMN IF NOT EXISTS "id" BIGINT;
ALTER TABLE "workspace_members" ADD COLUMN IF NOT EXISTS "workspace_id" TEXT;
ALTER TABLE "workspace_members" ADD COLUMN IF NOT EXISTS "user_id" TEXT;
ALTER TABLE "workspace_members" ADD COLUMN IF NOT EXISTS "role" TEXT DEFAULT 'workspace_viewer';
ALTER TABLE "workspace_members" ADD COLUMN IF NOT EXISTS "invited_by" TEXT;
ALTER TABLE "workspace_members" ADD COLUMN IF NOT EXISTS "joined_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);

-- workspaces
CREATE TABLE IF NOT EXISTS "workspaces" (
  "id" TEXT,
  "organization_id" TEXT,
  "name" TEXT,
  "slug" TEXT,
  "created_by" TEXT,
  "billing_type" TEXT DEFAULT 'client_billable',
  "billing_notes" TEXT,
  "billing_contact_email" TEXT,
  "billing_contract_ref" TEXT,
  "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint),
  PRIMARY KEY ("id")
);
ALTER TABLE "workspaces" ADD COLUMN IF NOT EXISTS "id" TEXT;
ALTER TABLE "workspaces" ADD COLUMN IF NOT EXISTS "organization_id" TEXT;
ALTER TABLE "workspaces" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "workspaces" ADD COLUMN IF NOT EXISTS "slug" TEXT;
ALTER TABLE "workspaces" ADD COLUMN IF NOT EXISTS "created_by" TEXT;
ALTER TABLE "workspaces" ADD COLUMN IF NOT EXISTS "billing_type" TEXT DEFAULT 'client_billable';
ALTER TABLE "workspaces" ADD COLUMN IF NOT EXISTS "billing_notes" TEXT;
ALTER TABLE "workspaces" ADD COLUMN IF NOT EXISTS "billing_contact_email" TEXT;
ALTER TABLE "workspaces" ADD COLUMN IF NOT EXISTS "billing_contract_ref" TEXT;
ALTER TABLE "workspaces" ADD COLUMN IF NOT EXISTS "created_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
ALTER TABLE "workspaces" ADD COLUMN IF NOT EXISTS "updated_at" BIGINT DEFAULT (EXTRACT(EPOCH FROM now())::bigint);
